version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cdc
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: interndb
      MYSQL_USER: user
      MYSQL_PASSWORD: cdcpassword
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
    driver: local